---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  #zones: us-east-2a, us-east-2b, us-east-2c
  #iopsPerGB: "10" 
  #fsType: ext4