apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgres-pv-volume
  labels:
    type: sc

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-storage-class
  hostPath:
   path: /var/lib/postgresql/data

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pv-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ebs-storage-class
  selector:
    matchLabels:
      type: sc
